# Generated by Django 5.0.1 on 2024-01-24 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название')),
                ('poster', models.ImageField(upload_to='poster_news/', verbose_name='Постер')),
                ('description', models.TextField(verbose_name='Описание')),
                ('male_description', models.TextField(verbose_name='Маленькое описание')),
                ('image', models.ImageField(upload_to='news/image/', verbose_name='Картинка для маленького описание')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
