# Generated by Django 5.0.1 on 2024-01-23 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trailers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailer',
            name='link',
            field=models.CharField(max_length=600, verbose_name='Ссылка на трейлер'),
        ),
    ]
