# Generated by Django 5.0.1 on 2024-01-18 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('celebrities', '0004_alter_director_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='height',
        ),
    ]
