# Generated by Django 5.0.1 on 2024-01-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebrities', '0005_remove_director_height'),
        ('movies', '0007_alter_movie_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='movies',
        ),
        migrations.AddField(
            model_name='director',
            name='movies',
            field=models.ManyToManyField(related_name='director', to='movies.movie', verbose_name='Фильмы которые снимал'),
        ),
    ]
