# Generated by Django 5.0.1 on 2024-01-22 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0007_alter_movie_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieMediaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=None, verbose_name='Картинка')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_image_media', to='movies.movie', verbose_name='Фильм')),
            ],
            options={
                'verbose_name': 'Медиа-картинка фильма',
                'verbose_name_plural': 'Медиа-картинки фильмов',
            },
        ),
    ]
