# Generated by Django 5.0.1 on 2024-01-22 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviemediaimage',
            name='image',
            field=models.ImageField(upload_to='error', verbose_name='Картинка'),
        ),
    ]
