# Generated by Django 5.0.1 on 2024-01-22 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_people', '0002_alter_moviemediaimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviemediaimage',
            name='image',
            field=models.ImageField(upload_to='<property object at 0x000001F34E12E340>/media/image', verbose_name='Картинка'),
        ),
    ]
