# Generated by Django 5.0.1 on 2024-01-23 07:55

import utils.get_media_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_people', '0006_alter_moviemediaimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviemediaimage',
            name='image',
            field=models.ImageField(upload_to=utils.get_media_path.upload_to_image_for_movie, verbose_name='Картинка'),
        ),
    ]
